Notification update to "2"

diff --git a/updateinfo b/updateinfo
--- a/updateinfo
+++ b/updateinfo
@@ -1,6 +1,43 @@
-newVersionScript="1"
+newVersionScript="2"
 noteLatestVersion="${GC}This is latest Version (Ver : ${newVersionScript})${WC}"
-noteUpdate=""
+noteUpdate="1. Add edit config.json on Account\n2. Add edit config.json on Game\n3. Add edit manual in Edit config.json\n4. Add Install Grasscutter"
 update() {
-    echo "New Version"
+    sudo apt update
+    isThisAndroid=$(uname -o)
+    if [[ $isThisAndroid = "Android" ]]; then
+        clear
+        echo "Please install on Ubuntu not Termux!"
+        exit 2
+    fi
+
+    if [ -f "/bin/gcandroid" ]; then
+        rm /bin/gcandroid
+    fi
+
+    folderName="zexUpdate"
+    mkdir $HOME/$folderName
+    cd $HOME/$folderName
+    if ! command -v wget &> /dev/null; then
+        sudo apt install wget
+    fi
+    echo "Download Script..."
+    sleep 1s
+    wget https://raw.githubusercontent.com/ElaXan/GCAndroid/main/Code/gcandroid.sh &> /dev/null
+    if [[ ! -f "gcandroid.sh" ]]; then
+        echo "Install Failed!"
+        exit 1
+    fi
+    mv gcandroid.sh /bin/gcandroid
+    chmod +x /bin/gcandroid
+    rm -rf $HOME/$folderName
+    if [ -f "/bin/gcandroid" ]; then
+        clear
+        echo "Update Success to Version : ${newVersionScript} !!"
+        echo "now enter command : gcandroid"
+        exit 0
+    else
+        clear
+        echo "Install Failed!"
+        exit 1
+    fi
 }
